artifact_root: artifact

data_ingestion:
  source_url: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  root_dir: artifact/dataset
  zip_data_file: artifact/dataset/data.zip
  unzip_data_file: artifact/dataset/

data_transformation:
  root_dir: artifact/dataset
  data_type: image
  transformed_data_file: artifact/dataset/transformed
  image_size: [224,224]
  unzip_data_file: artifact/dataset/



model_training:
  model_dir: artifact/model
  data_dir: artifact/dataset/transformed

model_evaluation:
  model_dir: artifact/model
  data_dir: artifact/dataset/transformed 
  