
services:
  airflow:
    build: 
      context: ..
      dockerfile: airflow/Dockerfile
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      PYTHONPATH: /opt/airflow/src
    volumes:
      - ./dags:/opt/airflow/dags
      - ./log:/opt/airflow/log            # DAGs
      - ../src:/opt/airflow/src                     # Local package
      - ../config:/opt/airflow/config               # Mount config directory
      - ../params:/opt/airflow/params               # Mount params directory
      - ../artifact:/opt/airflow/artifact
      - ../mlruns:/opt/airflow/mlruns
      - ../matrics:/opt/airflow/matrics
    ports:
      - "8080:8080"
    working_dir: /opt/airflow
    command: > 
      bash -c "
      airflow db init &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
      airflow scheduler & airflow webserver"
