name: MLOPS CI/CD

on: 
  push: 
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  mlops_pipeline:
    runs-on: ubuntu-latest  # Corrected from "unbut-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Reproduce pipeline
        run: |
          dvc repro



  docker-deploy:
    needs: mlops_pipeline
    runs-on: ubuntu-latest  # Corrected from "run-on"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Corrected the use of "run: actions/checkout"

      - name: Setup Docker builder
        uses: docker/setup-buildx-action@v2  # Corrected to v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Ensure you're using the latest version
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2  # Ensure you're using the correct version of the action
        with: 
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlops-template:latest
