name: MLOPS ci/cd

on: 
  push: 
    branches: 
      - main
  pull:
    branches:
      - main
jobs:
  mlops_pipeline:
    runs-on: unbut-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v4
        with: 
          python-version: 3.10
      
      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: reproduce pipeline
        run: |
          dvc repro

      - name: Run tests
        run: |
          pytest
  
  docker-deploy:
    needs: mlops_pipeline
    run-on: ubuntu-latest

    steps:
      
      - name: checkout code
        run: actions/checkout@v2

      - name: setup docker builder
        run: docker/setup-buildx-action@v3
      
      - name: login to docker hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: push to docker hub
        uses: docker/build-push-action@v5
        with: 
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlops-template:latest 